name: Nightly Autoware build

on:
  push:
    branches: master

  #schedule:
  #  - cron: "55 * * * *"

jobs:

  build-autoware-repos:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build AutowareAI image
      env:
        IMAGE_NAME: test_image
        ROS_DISTRO: melodic
        TAG_PREFIX: build_test
        VERSION: 1.13.0
      run: |
        docker login -u ${{ secrets.DKR_USR }} -p ${{ secrets.DKR_PASS }}
        cd generic
        ./build.sh -c off -i $IMAGE_NAME -r $ROS_DISTRO -t $TAG_PREFIX -v $VERSION
        docker image ls
        docker tag $IMAGE_NAME:$VERSION-$ROS_DISTRO-base ${{ secrets.DKR_USR }}/$IMAGE_NAME:$VERSION-$ROS_DISTRO-base
        docker tag $IMAGE_NAME:$VERSION-$ROS_DISTRO ${{ secrets.DKR_USR }}/$IMAGE_NAME:$VERSION-$ROS_DISTRO
        docker push ${{ secrets.DKR_USR }}/$IMAGE_NAME:$VERSION-$ROS_DISTRO-base
        docker push ${{ secrets.DKR_USR }}/$IMAGE_NAME:$VERSION-$ROS_DISTRO
