name: Nightly Autoware build

on:
  push:
    branches: master

  schedule:
    - cron: "55 * * * *"

jobs:

  build-autoware-repos:

    runs-on: ubuntu-latest
    steps:

    - name: Setup ROS
      uses: ros-tooling/setup-ros@0.0.18
      with:
        required-ros-distributions: melodic

    - name: Build AutowareAI
        run: |
          source /opt/ros/melodic/setup.bash
          mkdir -p autoware.ai/src
          cd autoware.ai
          wget -O autoware.ai.repos "https://gitlab.com/autowarefoundation/autoware.ai/autoware/raw/master/autoware.ai.repos?inline=false"
          vcs import src < autoware.ai.repos
          rosdep update
          rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
