name: Arm64 Docker build

on:
  push:
    branches: test_branch

jobs:

  build-docker-image:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Check Docker version
      run: |
        docker version
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker buildx --help

    - name: Register arm executables
      run: |
        docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
        cat /proc/sys/fs/binfmt_misc/qemu-aarch64

    - name: Create multi-arch build instance
      run: |
        docker buildx create --name mybuilder
        docker buildx use mybuilder
        docker buildx inspect --bootstrap

    - name: Buildx
      run: |
        docker login -u ${{ secrets.DKR_USR }} -p ${{ secrets.DKR_PASS }}
        docker buildx build --platform linux/arm64,linux/amd64 -t ${{ secrets.DKR_USR }}/hello --build-arg ROS_DISTRO=melodic  . --push
